--- #YAML:1.0
name:                Net-IDN-tools
version:             0.99_20080913
abstract:            modules for handling of Internationalised Domain Names in Applications (IDNA)
license:             ~
author:              
    - Claus Färber <CFAERBER@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Unicode::Stringprep:           1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
