# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IDN-tools
version:      0.99_20071012.1
version_from: lib/Net/IDN/Encode.pm
installdirs:  site
requires:
    Unicode::Stringprep:           1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
